import type { Customer, CustomerFormData } from '@/types/customer';

export const emptyCustomerFormData: CustomerFormData = {
  customer_type: 'business',
  logo_url: null,
  email: '',
  phone: '',
  address_line1: '',
  address_line2: '',
  city: '',
  state: '',
  postcode: '',
  country: '',
  status: 'active',
  legal_name: '',
  trading_name: '',
  registration_number: '',
  vat_number: '',
  tax_scheme: '',
  credit_rating: '',
  risk_category: '',
  payment_terms: '',
  credit_limit: undefined,
  credit_hold: false,
  currency: '',
  price_list_id: '',
  discount_rate: undefined,
  tax_inclusive: false,
  default_warehouse_id: '',
  delivery_instructions: '',
  preferred_carrier: '',
  shipping_account_number: '',
  incoterms: '',
  sales_rep_id: '',
  channel: '',
  region: '',
  forecast_group: '',
  demand_profile: '',
  metadata: {},
};

/** Display-only customer row for create-mode summary card (not persisted). */
export function formDataToCustomerPreview(
  formData: CustomerFormData,
  tenantId: string = ''
): Customer {
  const now = new Date().toISOString();
  return {
    id: '',
    tenant_id: tenantId,
    customer_code: null,
    customer_type: formData.customer_type ?? 'business',
    logo_url: formData.logo_url?.trim() || null,
    email: formData.email.trim() || '',
    phone: formData.phone?.trim() || null,
    address_line1: formData.address_line1?.trim() || null,
    address_line2: formData.address_line2?.trim() || null,
    city: formData.city?.trim() || null,
    state: formData.state?.trim() || null,
    postcode: formData.postcode?.trim() || null,
    country: formData.country?.trim() || null,
    status: formData.status ?? 'active',
    legal_name: formData.legal_name?.trim() || 'New customer',
    trading_name: formData.trading_name?.trim() || null,
    registration_number: formData.registration_number?.trim() || null,
    vat_number: formData.vat_number?.trim() || null,
    tax_scheme: formData.tax_scheme?.trim() || null,
    credit_rating: formData.credit_rating?.trim() || null,
    risk_category: formData.risk_category?.trim() || null,
    payment_terms: formData.payment_terms?.trim() || null,
    credit_limit: formData.credit_limit ?? null,
    credit_hold: formData.credit_hold ?? false,
    currency: formData.currency?.trim() || null,
    price_list_id: formData.price_list_id?.trim() || null,
    discount_rate: formData.discount_rate ?? null,
    tax_inclusive: formData.tax_inclusive ?? false,
    default_warehouse_id: formData.default_warehouse_id?.trim() || null,
    delivery_instructions: formData.delivery_instructions?.trim() || null,
    preferred_carrier: formData.preferred_carrier?.trim() || null,
    shipping_account_number: formData.shipping_account_number?.trim() || null,
    incoterms: formData.incoterms?.trim() || null,
    sales_rep_id: formData.sales_rep_id?.trim() || null,
    channel: formData.channel?.trim() || null,
    region: formData.region?.trim() || null,
    forecast_group: formData.forecast_group?.trim() || null,
    demand_profile: formData.demand_profile?.trim() || null,
    metadata: formData.metadata ?? {},
    version: 0,
    created_at: now,
    updated_at: now,
    created_by: null,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
  };
}
