import type { LucideIcon } from 'lucide-react';
import {
  BarChart3,
  BarChart2,
  BookOpen,
  Boxes,
  Building,
  Calendar,
  FileBarChart,
  FileSpreadsheet,
  FileText,
  GitBranch,
  HelpCircle,
  Layers,
  List,
  MapPin,
  Navigation,
  Package,
  PackageCheck,
  PackagePlus,
  PackageX,
  PieChart,
  Plug,
  RotateCcw,
  Settings,
  ShoppingCart,
  TrendingUp,
  Truck,
  User,
  Users,
  Warehouse,
  Zap,
  ArrowLeftRight,
  ClipboardCheck,
  ClipboardList,
} from 'lucide-react';

export type NavIconPillar = 'analytics' | 'businessCore' | 'execution' | 'other';

export function getIconAndPillarForNavLabel(label: string): {
  icon: LucideIcon;
  pillar: NavIconPillar;
} {
  const iconMap: Record<string, { icon: LucideIcon; pillar: NavIconPillar }> = {
    'Business Core': { icon: Plug, pillar: 'businessCore' },
    Execution: { icon: Zap, pillar: 'execution' },
    Analytics: { icon: BarChart3, pillar: 'analytics' },

    Calendar: { icon: Calendar, pillar: 'businessCore' },
    Product: { icon: Package, pillar: 'businessCore' },
    'Bills of Materials': { icon: Layers, pillar: 'businessCore' },
    Supplier: { icon: Truck, pillar: 'businessCore' },
    Warehouse: { icon: Warehouse, pillar: 'businessCore' },
    'Stock Adjustments': { icon: ClipboardList, pillar: 'businessCore' },
    'Stock Count': { icon: ClipboardCheck, pillar: 'businessCore' },
    'Stock Transfer': { icon: ArrowLeftRight, pillar: 'businessCore' },
    'Purchase Management': { icon: ShoppingCart, pillar: 'businessCore' },
    'Purchase Orders': { icon: FileSpreadsheet, pillar: 'businessCore' },
    'Goods Receipt': { icon: PackageCheck, pillar: 'businessCore' },
    'Purchase Invoices': { icon: FileText, pillar: 'businessCore' },
    'Goods Return': { icon: PackageX, pillar: 'businessCore' },
    'Purchase Returns': { icon: PackageX, pillar: 'businessCore' },
    Customer: { icon: Users, pillar: 'businessCore' },
    Customers: { icon: Users, pillar: 'businessCore' },
    Products: { icon: Package, pillar: 'businessCore' },
    'Delivery Locations': { icon: MapPin, pillar: 'businessCore' },
    'Order Management': { icon: PackagePlus, pillar: 'businessCore' },
    'Sales Orders': { icon: FileSpreadsheet, pillar: 'businessCore' },
    'Order Fulfillment': { icon: PackageCheck, pillar: 'businessCore' },
    'Sales Invoice': { icon: FileText, pillar: 'businessCore' },
    'Sales Invoices': { icon: FileText, pillar: 'businessCore' },
    'Sales Returns': { icon: RotateCcw, pillar: 'businessCore' },
    'Customer Weeks': { icon: Calendar, pillar: 'businessCore' },

    'Planning Board': { icon: GitBranch, pillar: 'execution' },
    Scheduler: { icon: Calendar, pillar: 'execution' },
    'Material Requirement Plan (MRP)': { icon: Layers, pillar: 'execution' },
    MRP: { icon: Layers, pillar: 'execution' },
    'Product Movement': { icon: Zap, pillar: 'execution' },

    Forecast: { icon: TrendingUp, pillar: 'analytics' },
    'Forecast Model': { icon: BarChart2, pillar: 'analytics' },
    'Customer Forecast': { icon: TrendingUp, pillar: 'analytics' },
    'Cost File': { icon: FileText, pillar: 'analytics' },
    'Cost of Goods': { icon: FileBarChart, pillar: 'analytics' },
    'Logistics Costs': { icon: Truck, pillar: 'analytics' },
    Inventory: { icon: Boxes, pillar: 'analytics' },
    'Material Variance': { icon: BarChart2, pillar: 'analytics' },
    'Working Capital': { icon: PieChart, pillar: 'analytics' },
    'P&L': { icon: FileBarChart, pillar: 'analytics' },
    Reports: { icon: BookOpen, pillar: 'analytics' },

    'User Profile': { icon: User, pillar: 'other' },
    Profile: { icon: User, pillar: 'other' },
    Administration: { icon: Settings, pillar: 'other' },
    'Navigation Manager': { icon: Navigation, pillar: 'other' },
    Users: { icon: Users, pillar: 'other' },
    'User Groups': { icon: Users, pillar: 'other' },
    'Tenants Hub': { icon: Building, pillar: 'other' },
    'Tenant Management': { icon: Settings, pillar: 'other' },
    'Tenants List': { icon: List, pillar: 'other' },
    Account: { icon: Users, pillar: 'other' },
    Help: { icon: HelpCircle, pillar: 'other' },
  };

  return iconMap[label] ?? { icon: BarChart3, pillar: 'other' };
}
